services:
  - type: web
    name: indoor-navigator
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
